variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/psono/psono-client:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/psono/psono-client:latest

stages:
  - test
  - build
  - release
  - deploy

unittests:
  stage: test
  image: ubuntu:16.04
  script:
    - sh ./var/build-ubuntu.sh
    - karma start ./unittests/karma-phantom.conf.js

linter:
  stage: test
  image: ubuntu:16.04
  script:
    - sh ./var/build-ubuntu.sh
    - cat ./build/firefox/manifest.json
    - addons-linter ./build/firefox


docker-image:
  stage: build
  image: ubuntu:16.04
  services:
    - docker:dind
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
  script:
    - sh ./var/build-ubuntu.sh
    - set -x && curl -fSL "https://get.docker.com/builds/Linux/x86_64/docker-1.12.0.tgz" -o docker.tgz && echo "3dd07f65ea4a7b4c8829f311ab0213bca9ac551b5b24706f3e79a97e22097f8b *docker.tgz" | sha256sum -c - && tar -xzvf docker.tgz && mv docker/* /usr/local/bin/
    - docker info
    - gulp
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

firefox-extension:
  stage: build
  script:
    - sh ./var/build-ubuntu.sh
    - sh ./var/build-firefox-extension.sh
  artifacts:
    paths:
    - dist/chrome/psono.firefox.PW.zip

chrome-extension:
  stage: build
  script:
    - sh ./var/build-ubuntu.sh
    - sh ./var/build-chrome-extension.sh
  artifacts:
    paths:
    - dist/chrome/psono.chrome.PW.zip

job-release-docker:
  stage: release
  image: docker:git
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

job-deploy:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - sh ./var/deploy.sh
  environment:
    name: production
    url: https://psono.pw
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

job-deploy-chrome:
  stage: deploy
  image: ubuntu:16.04
  script:
    - sh ./var/build-ubuntu.sh
    - sh ./var/build-chrome-extension.sh
    - sh ./var/deploy-chrome-extension.sh
  environment:
    name: chrome-webstore
    url: https://chrome.google.com/webstore/detail/psonopw/eljmjmgjkbmpmfljlmklcfineebidmlo
  when: manual
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

job-deploy-firefox:
  stage: deploy
  image: ubuntu:16.04
  script:
    - sh ./var/build-ubuntu.sh
    - sh ./var/build-firefox-extension.sh
    - sh ./var/deploy-firefox-extension.sh
  environment:
    name: firefox-webstore
    url: https://addons.mozilla.org/de/firefox/addon/psono-pw-password-manager/
  when: manual
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
