variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/psono/psono-client:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/psono/psono-client:latest

stages:
  - test
  - build
  - release
  - deploy

unittests:
  stage: test
  script:
    - sh build-ubuntu.sh
    - karma start ./unittests/karma-phantom.conf.js


# No saas support in alpine (docker:git) image
#docker-image:
#  stage: build
#  image: docker:git
#  services:
#  - docker:dind
#  script:
#  - docker info
#  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
#  - docker build -t $CONTAINER_TEST_IMAGE .
#  - docker push $CONTAINER_TEST_IMAGE


# Works as soon as https://github.com/sass/node-sass/issues/1589 is solved
#docker-image:
#  stage: build
#  services:
#  - docker:dind
#  script:
#  - docker info
#  - sh build-ubuntu.sh
#  - gulp
#  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
#  - docker build -t $CONTAINER_TEST_IMAGE .
#  - docker push $CONTAINER_TEST_IMAGE



docker-image:
  stage: build
  image: ubuntu:16.04
  services:
  - docker:dind
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
  script:
  - apt-get update
  - apt-get install apt-transport-https ca-certificates curl openssl
  - set -x && curl -fSL "https://get.docker.com/builds/Linux/x86_64/docker-1.12.0.tgz" -o docker.tgz && echo "3dd07f65ea4a7b4c8829f311ab0213bca9ac551b5b24706f3e79a97e22097f8b *docker.tgz" | sha256sum -c - && tar -xzvf docker.tgz && mv docker/* /usr/local/bin/
  - docker info
  - sh build-ubuntu.sh
  - gulp
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE

firefox-extension:
  stage: build
  script:
  - sh build-ubuntu.sh
  - cd build/firefox/ && jpm xpi && cd ../../ && cp /builds/psono/psono-client/build/firefox/psonopw.xpi "$CI_BUILD_REF_NAME.psono.PW.firefox.xpi"
  artifacts:
    paths:
    - "$CI_BUILD_REF_NAME.psono.PW.firefox.xpi"

chrome-extension:
  stage: build
  script:
  - sh build.sh
  artifacts:
    paths:
    - build/chrome/

job-release-docker:
  stage: release
  image: docker:git
  services:
  - docker:dind
  script:
  - docker info
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.gitlab.com
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

#job-release-artifacts:
#  stage: release
#  image: docker:git
#  services:
#  - docker:dind
#  script:
#    - sh build.sh
#    - gulp xpiunsigned
#  only:
#    - master

job-deploy:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master


#before_script:
#  - docker info
#  - /usr/local/bin/docker-compose -f docker-compose-test.yml kill
#  - /usr/local/bin/docker-compose -f docker-compose-test.yml rm -f
#  - /usr/local/bin/docker-compose -f docker-compose-test.yml build

#test_image_chrome:
#  script:
#    - /usr/local/bin/docker-compose -f docker-compose-test.yml run password-client-image-test bash -c "(test -e /tmp/.X99-lock || /usr/bin/Xvfb :99 &) && karma start ./unittests/karma-chrome.conf.js"
#    - /usr/local/bin/docker-compose -f docker-compose-test.yml stop
#
#test_image_firefox:
#  script:
#    - /usr/local/bin/docker-compose -f docker-compose-test.yml run password-client-image-test bash -c "(test -e /tmp/.X99-lock || /usr/bin/Xvfb :99 &) && karma start ./unittests/karma-firefox.conf.js"
#    - /usr/local/bin/docker-compose -f docker-compose-test.yml stop